FROM node:12.19.0-alpine
LABEL maintainer="Doni Rubiagatra <doni@zero-one-group.com"

RUN apk add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

RUN npm i -g firebase-tools
