(defproject api "0.1.0-SNAPSHOT"
  :dependencies [[buddy/buddy-auth "2.2.0"]
                 [buddy/buddy-core "1.6.0"]
                 [buddy/buddy-hashers "1.4.0"]
                 [buddy/buddy-sign "3.1.0"]
                 [ch.qos.logback/logback-classic "1.2.3"]
                 [cheshire "5.10.0"]
                 [clojure.java-time "0.3.2"]
                 [com.fasterxml.jackson.core/jackson-core "2.11.2"]
                 [com.fasterxml.jackson.core/jackson-databind "2.11.2"]
                 [conman "0.9.0"]
                 [cprop "0.1.17"]
                 [expound "0.8.5"]
                 [failjure "2.0.0"]
                 [funcool/struct "1.4.0"]
                 [luminus-http-kit "0.1.8"]
                 [luminus-migrations "0.6.7"]
                 [luminus-transit "0.1.2"]
                 [luminus/ring-ttl-session "0.3.3"]
                 [markdown-clj "1.10.5"]
                 [metosin/jsonista "0.2.6"]
                 [metosin/muuntaja "0.6.7"]
                 [metosin/reitit "0.5.5"]
                 [metosin/ring-http-response "0.9.1"]
                 [mount "0.1.16"]
                 [nrepl "0.8.0"]
                 [org.clojure/clojure "1.10.1"]
                 [org.clojure/clojurescript "1.10.597"]
                 [org.clojure/tools.cli "1.0.194"]
                 [org.clojure/tools.logging "1.1.0"]
                 [org.postgresql/postgresql "42.2.14"]
                 [org.webjars.npm/bulma "0.9.0"]
                 [org.webjars.npm/material-icons "0.3.1"]
                 [org.webjars/webjars-locator "0.40"]
                 [ring-webjars "0.2.0"]
                 [ring/ring-core "1.8.1"]
                 [ring/ring-defaults "0.3.2"]
                 [selmer "1.12.28"]
                 [com.taoensso/carmine "2.19.1"]
                 [zero.one/fxl "0.0.5"]]
  :plugins [[lein-cloverage "1.1.2"]
            [lein-cljfmt "0.6.7"]
            [lein-exec "0.3.7"]]
  :profiles {:project/dev  {:dependencies [[pjstadig/humane-test-output "0.10.0"]
                                           [prone "2020-01-17"]
                                           [ring/ring-devel "1.8.1"]
                                           [ring/ring-mock "0.4.0"]]
                            :plugins      [[com.jakemccrary/lein-test-refresh "0.24.1"]
                                           [jonase/eastwood "0.3.5"]]}})
